### ISSUE TITLE
Update async-std to v1.6.2

### ISSUE THREAD

**Issue by shekohex** [sunshine-protocol/sunshine#18]
`async-std` needs to be updated to the latest version, currently, I couldn't compile `sunshine-ffi`

```text
 Updating crates.io index
    Updating git repository `https://github.com/sunshine-protocol/sunshine-bounty`
    Updating git repository `https://github.com/sunshine-protocol/sunshine`
    Updating git repository `https://github.com/sunshine-protocol/frusty-logger`
    Updating git repository `https://github.com/sunshine-protocol/sunshine-identity`
error: failed to select a version for `async-std`.
    ... required by package `sunshine-client v0.1.0 (https://github.com/sunshine-protocol/sunshine#f3a25c35)`
    ... which is depended on by `sunshine v0.1.0 (Code\sunshine-bounty-ui\native\sunshine)`
versions that meet the requirements `=1.5.0` are: 1.5.0

all possible versions conflict with previously selected packages.

  previously selected package `async-std v1.6.2`
    ... which is depended on by `sunshine v0.1.0 (Code\sunshine-bounty-ui\native\sunshine)`

failed to select a version for `async-std` which could resolve this conflict
```
My Cargo.toml
```toml

[dependencies]
identity-ffi = { git = "https://github.com/sunshine-protocol/sunshine-identity", package = "sunshine-identity-ffi", features = ["faucet"] }
bounty-ffi = { git = "https://github.com/sunshine-protocol/sunshine-bounty", package = "sunshine-bounty-ffi" }
frusty-logger = { git =  "https://github.com/sunshine-protocol/frusty-logger" }
client = { git = "https://github.com/sunshine-protocol/sunshine", package = "sunshine-client" }
log = "^0.4"
```
